import { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, ChevronDown, LifeBuoy } from 'lucide-react';
import { PublicLayout } from '../components/layout/PublicLayout.jsx';
import { Card, Button, Input } from '../components/ui/index.js';
import { cn } from '../utils/cn.js';
import { Link } from 'react-router-dom';

const faqItems = [
  // Getting Started
  {
    category: 'Getting Started',
    question: 'How do I create my ZenBooking account?',
    answer: 'Click Get Started Free on the homepage, fill in your name email password business name and business type, our AI will automatically generate a professional description for your booking page and your account will be ready in seconds.'
  },
  {
    category: 'Getting Started',
    question: 'How do I share my booking page with customers?',
    answer: 'After logging in go to Dashboard or Settings where you will find your unique booking link, copy it and share it anywhere such as your Instagram bio, WhatsApp status, Google Business profile, or directly message it to customers.'
  },
  {
    category: 'Getting Started',
    question: 'Do my customers need to create an account to book?',
    answer: 'No, customers never need to create an account, they simply visit your booking link, pick a date and time, enter their name and phone number, and the booking is confirmed instantly.'
  },
  // For Business Owners
  {
    category: 'For Business Owners',
    question: 'How do I set my available hours?',
    answer: 'Go to the Slots page in your dashboard, you will see a row for each day of the week Monday through Sunday, toggle on the days you work, set your start time and end time for each day, choose your appointment duration such as 30 or 60 minutes, and click Save Schedule.'
  },
  {
    category: 'For Business Owners',
    question: 'How do I block a date like a holiday?',
    answer: 'On the Slots page scroll down to the Blocked Dates section, pick the date you want to block, optionally add a reason, and click Block Date, customers will not be able to book on that date.'
  },
  {
    category: 'For Business Owners',
    question: 'Can I reschedule or cancel a customer booking?',
    answer: 'Yes, go to the Bookings page, find the booking you want to change, click the three dot menu on the booking card, and choose either Reschedule to pick a new date and time or Cancel to cancel the appointment, the customer will be notified automatically.'
  },
  // Bookings
  {
    category: 'Bookings',
    question: 'Will customers receive a confirmation after booking?',
    answer: 'Yes, as soon as a booking is confirmed both the customer and you as the business owner receive an email confirmation with all the booking details.'
  },
  {
    category: 'Bookings',
    question: 'Are reminder messages sent automatically?',
    answer: 'Yes, ZenBooking sends an AI written personalised reminder message to the customer one hour before their appointment, the reminder is generated by Groq AI and is unique to each customer rather than a generic template.'
  },
  {
    category: 'Bookings',
    question: 'What happens if two customers try to book the same slot at the same time?',
    answer: 'ZenBooking uses an atomic database check that guarantees only one booking can exist per slot, if two customers submit at the exact same moment one will get a confirmation and the other will see a message saying the slot was just taken and be prompted to choose another time.'
  },
  // AI Features
  {
    category: 'AI Features',
    question: 'How does the AI chatbot booking work?',
    answer: 'On your public booking page there is a floating chat button in the bottom right corner, customers can click it and type naturally for example I want a haircut tomorrow afternoon, the Groq AI understands the request, finds available slots matching the time preference, and guides the customer through confirming the booking conversationally without them needing to use the calendar manually.'
  },
  {
    category: 'AI Features',
    question: 'What are AI Insights?',
    answer: 'In your dashboard under AI Insights you can click Generate Insights and Groq AI will analyse your last 90 days of booking data including busiest days, peak hours, cancellation patterns, and trends, then give you plain English recommendations to help you optimise your schedule and reduce no-shows.'
  },
  {
    category: 'AI Features',
    question: 'How is my business description generated?',
    answer: 'When you register Groq AI automatically writes a professional three sentence description for your booking page based on your business name and type, you can edit this description anytime in Settings and regenerate it with one click if you want a fresh version.'
  },
  // Account and Billing
  {
    category: 'Account and Billing',
    question: 'Is ZenBooking free to use?',
    answer: 'Yes ZenBooking is currently free for individual business owners, you can create your account set up your booking page and accept unlimited bookings at no cost.'
  },
  {
    category: 'Account and Billing',
    question: 'How do I change my password?',
    answer: 'Go to Settings in your dashboard, scroll to the Change Password section, enter your current password and then your new password twice, and click Save.'
  },
  {
    category: 'Account and Billing',
    question: 'How do I delete my account?',
    answer: 'To delete your account please contact us at support@zenbooking.app with your registered email address, we will process your deletion request within 30 days and permanently remove all your data.'
  }
];

const categories = ['All', 'Getting Started', 'For Business Owners', 'Bookings', 'AI Features', 'Account and Billing'];

const FAQItem = ({ item, isOpen, onToggle }) => (
  <Card className="border border-white/10 bg-white/5 overflow-hidden">
    <button
      onClick={onToggle}
      className="w-full px-6 py-4 flex items-center justify-between hover:bg-white/10 transition-colors"
    >
      <span className="font-medium text-slate-900 dark:text-white text-left">{item.question}</span>
      <motion.div
        animate={{ rotate: isOpen ? 180 : 0 }}
        transition={{ duration: 0.2 }}
      >
        <ChevronDown className="h-5 w-5 text-slate-400" />
      </motion.div>
    </button>

    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ height: 0, opacity: 0 }}
          animate={{ height: 'auto', opacity: 1 }}
          exit={{ height: 0, opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="border-t border-white/10"
        >
          <p className="px-6 py-4 text-slate-600 dark:text-slate-300 leading-relaxed">
            {item.answer}
          </p>
        </motion.div>
      )}
    </AnimatePresence>
  </Card>
);

const HelpPage = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [expandedIndex, setExpandedIndex] = useState(null);

  const filteredItems = useMemo(() => {
    return faqItems.filter(item => {
      const matchesSearch = searchTerm === '' || 
        item.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.answer.toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesCategory = selectedCategory === 'All' || item.category === selectedCategory;
      
      return matchesSearch && matchesCategory;
    });
  }, [searchTerm, selectedCategory]);

  return (
    <PublicLayout>
      <div className="min-h-screen bg-surface-950 pt-20">
        {/* Hero Section */}
        <section className="relative overflow-hidden py-12">
          <div className="absolute left-[-10%] top-[-15%] h-96 w-96 rounded-full bg-primary-500/20 blur-3xl animate-blob" />
          <div className="absolute right-[-8%] bottom-[-10%] h-[28rem] w-[28rem] rounded-full bg-accent-500/20 blur-3xl animate-blob" />

          <div className="mx-auto max-w-4xl px-4 text-center py-12 sm:px-6 lg:px-8 relative z-10">
            <div className="flex justify-center mb-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-gradient-to-br from-primary-500 to-accent-500 text-white">
                <Search className="h-6 w-6" />
              </div>
            </div>
            <h1 className="text-4xl font-extrabold text-white">
              How can we help you?
            </h1>
            <p className="mt-4 text-lg text-slate-300">
              Find answers to common questions about ZenBooking
            </p>

            {/* Search Input */}
            <div className="mt-8 max-w-2xl mx-auto">
              <div className="relative">
                <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 h-5 w-5 text-slate-400" />
                <input
                  type="text"
                  placeholder="Search for answers..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className={cn(
                    'w-full rounded-xl border px-12 py-4 bg-white/5 text-white placeholder:text-slate-400',
                    'border-white/10 transition-colors duration-200',
                    'focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500/20',
                    'dark:bg-white/5 dark:border-white/10 dark:text-white'
                  )}
                />
              </div>
            </div>
          </div>
        </section>

        {/* Category Filter */}
        <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
          <div className="flex flex-wrap gap-2">
            {categories.map((category) => (
              <button
                key={category}
                onClick={() => setSelectedCategory(category)}
                className={cn(
                  'px-4 py-2 rounded-full text-sm font-medium transition-colors',
                  selectedCategory === category
                    ? 'bg-gradient-to-r from-primary-500 to-accent-500 text-white'
                    : 'bg-white/5 text-slate-300 hover:bg-white/10 border border-white/10'
                )}
              >
                {category}
              </button>
            ))}
          </div>
        </section>

        {/* FAQ Items */}
        <section className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
          {filteredItems.length > 0 ? (
            <div className="space-y-4">
              {filteredItems.map((item, idx) => (
                <FAQItem
                  key={`${item.category}-${idx}`}
                  item={item}
                  isOpen={expandedIndex === idx}
                  onToggle={() => setExpandedIndex(expandedIndex === idx ? null : idx)}
                />
              ))}
            </div>
          ) : (
            <div className="text-center py-12">
              <p className="text-slate-400">No results found for your search.</p>
              <button
                onClick={() => {
                  setSearchTerm('');
                  setSelectedCategory('All');
                }}
                className="mt-4 text-primary-400 hover:text-primary-300 font-medium"
              >
                Clear filters
              </button>
            </div>
          )}
        </section>

        {/* Still Need Help Card */}
        <section className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
          <Card className="border border-gradient-to-r from-primary-500/50 to-accent-500/50 bg-gradient-to-br from-primary-500/10 to-accent-500/10 p-8">
            <div className="flex items-start gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-gradient-to-br from-primary-500 to-accent-500 text-white flex-shrink-0">
                <LifeBuoy className="h-6 w-6" />
              </div>
              <div className="flex-1">
                <h3 className="text-2xl font-bold text-white">Still have questions?</h3>
                <p className="mt-2 text-slate-300">Our team is here to help</p>
                <Link to="/contact">
                  <Button className="mt-6">Contact Us</Button>
                </Link>
              </div>
            </div>
          </Card>
        </section>
      </div>
    </PublicLayout>
  );
};

export { HelpPage };
